"""add stock tables

Revision ID: 14de452cc4b7
Revises: 90d11f571e75
Create Date: 2025-03-07 12:05:49.984437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14de452cc4b7'
down_revision: Union[str, None] = '90d11f571e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('date', 'symbol', name=op.f('pk_daily_data'))
    )
    op.create_table('minute_data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', name=op.f('pk_minute_data'))
    )
    op.create_table('minute_kline',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('adjust_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minute_kline'))
    )
    op.create_table('stock_info',
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('symbol', name=op.f('pk_stock_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_info')
    op.drop_table('minute_kline')
    op.drop_table('minute_data')
    op.drop_table('daily_data')
    # ### end Alembic commands ###
