"""add stock tables

Revision ID: 90d11f571e75
Revises: 13a5777c54a0
Create Date: 2025-03-07 12:01:39.666233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d11f571e75'
down_revision: Union[str, None] = '13a5777c54a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_info')
    op.drop_table('daily_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_data',
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('open', sa.FLOAT(), nullable=True),
    sa.Column('high', sa.FLOAT(), nullable=True),
    sa.Column('low', sa.FLOAT(), nullable=True),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.Column('volume', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )
    op.create_table('stock_info',
    sa.Column('symbol', sa.VARCHAR(length=10), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=10), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=50), nullable=True),
    sa.Column('list_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###
